import simfin.names as sf_cols

PAST_YEARS_REQUESTED = 'Past Years Requested'
TICKER = sf_cols.TICKER
COMPANY_NAME = sf_cols.COMPANY_NAME
INDUSTRY_ID = sf_cols.INDUSTRY_ID
REPORT_DATE = sf_cols.REPORT_DATE
TARGET_TICKER = 'Target Ticker'
PEER_TICKER = 'Peer Ticker'
EPS_BREAKING = 'EPS Breaking'
REVENUE_BREAKING = 'Revenue Breaking'
EPS_FORECAST = 'EPS Forecast'
REVENUE_FORECAST = 'Revenue Forecast'
SIMFIN_SCHEMA = 'Simfin Schema'
PEER_WEIGHT = 'Peer Weight'
PEER_LIST = 'Peer List'
EVALUATE = 'Evaluate'
LAST_REPORT_DATE = 'Last Report Date'
FIRST_REPORT_DATE = 'First Report Date'
QTR_EPS = 'Quarterly EPS'
TTM_QTR_EPS = 'TTM Quarterly EPS'
QTR_PE_RATIO = 'Quarterly PE Ratio'
TTM_QTR_PE_RATIO = 'TTM Quarterly PE Ratio'
MU_QTR_PE_RATIO = 'Mu Quarterly PE Ratio'
MU_TTM_QTR_PE_RATIO = 'Mu TTM Quarterly PE Ratio'
K_PEER_WEIGHT = 'K_PEER_WEIGHT'
K_QTR_PE = 'K_QTR_PE'
K_TTM_QTR_PE = 'K_TTM_QTR_PE'
K_PEER_QTR_PE = 'K_PEER_QTR_PE'
K_PEER_TTM_QTR_PE = 'K_PEER_TTM_QTR_PE'
K_TARGET_QTR_PE = 'K_TARGET_QTR_PE'
K_TARGET_TTM_QTR_PE = 'K_TARGET_TTM_QTR_PE'
MU_NUM_YEARS = 'Mu Number of Years'
